# Generated by Django 5.0.4 on 2024-04-13 15:31

import django.utils.timezone
import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userprofile_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthDate',
            field=models.DateField(default=django.utils.timezone.now, validators=[user.models.validate_birth_date]),
        ),
    ]
